# version: '3.8'  # removed obsolete

services:
  db:
    image: postgres:16-alpine3.19
    restart: always
    environment:
      POSTGRES_DB: meuapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/meuapp
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data:
