FROM node:20-alpine3.19

WORKDIR /app

# Copy package files
COPY backend/package*.json ./

RUN npm ci --only=production

# Copy source code
COPY backend/ ./

USER node

EXPOSE 3000

CMD ["npm", "start"]
