-- CRM + CPM + MENSAGERIA COMPLETA - WEBSIDE SISTEMAS
-- MySQL Schema Completo
-- Generated by BLACKBOXAI

-- ========================================
-- 1. TABELAS BASE (ESTRUTURA ORGANIZACIONAL)
-- ========================================

CREATE TABLE `filial` (
  `id_filial` bigint NOT NULL AUTO_INCREMENT,
  `cnpj` varchar(20) NOT NULL,
  `razao_social` varchar(255) NOT NULL,
  `nome_fantasia` varchar(255),
  `telefone` varchar(20),
  `whatsapp` varchar(20),
  `email` varchar(255),
  `base_sm` decimal(10,2) NOT NULL DEFAULT '1412.00',
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `data_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_filial`),
  UNIQUE KEY `uk_cnpj` (`cnpj`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `departamento` (
  `id_departamento` bigint NOT NULL AUTO_INCREMENT,
  `id_filial` bigint NOT NULL,
  `nome` varchar(100) NOT NULL,
  `descricao` text,
  `id_responsavel` bigint,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `data_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_departamento`),
  KEY `fk_departamento_filial` (`id_filial`),
  KEY `fk_departamento_responsavel` (`id_responsavel`),
  CONSTRAINT `fk_departamento_filial` FOREIGN KEY (`id_filial`) REFERENCES `filial` (`id_filial`),
  CONSTRAINT `fk_departamento_responsavel` FOREIGN KEY (`id_responsavel`) REFERENCES `colaborador` (`id_colaborador`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `perfil_acesso` (
  `id_perfil` bigint NOT NULL AUTO_INCREMENT,
  `nome_perfil` varchar(100) NOT NULL,
  `nivel_acesso` int NOT NULL DEFAULT '1',
  `descricao` text,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_perfil`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `status` (
  `id_status` bigint NOT NULL AUTO_INCREMENT,
  `nome_status` varchar(100) NOT NULL,
  `tipo_entidade` enum('lead','cliente','orcamento','pedido','contrato','aditivo','fatura','implantacao','comissao','tarefa','automacao_regra','mensagem_envio','colaborador') NOT NULL,
  `descricao` text,
  `ordem_exibicao` int DEFAULT '0',
  `cor_hex` varchar(7) DEFAULT '#3B82F6',
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_status`),
  UNIQUE KEY `uk_status_tipo_nome` (`tipo_entidade`,`nome_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `endereco` (
  `id_endereco` bigint NOT NULL AUTO_INCREMENT,
  `tipo` enum('filial','lead','cliente','colaborador','grupo_economico') NOT NULL,
  `id_referencia` bigint NOT NULL,
  `cep` varchar(10),
  `tipo_logradouro` varchar(50),
  `logradouro` varchar(255),
  `numero` varchar(20),
  `complemento` varchar(255),
  `bairro` varchar(100),
  `cidade` varchar(100),
  `estado` char(2),
  `pais` varchar(50) DEFAULT 'Brasil',
  `data_cadastro` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_endereco`),
  KEY `idx_endereco_tipo_ref` (`tipo`,`id_referencia`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `grupo_economico` (
  `id_grupo` bigint NOT NULL AUTO_INCREMENT,
  `nome_grupo` varchar(255) NOT NULL,
  `descricao` text,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `id_endereco` bigint,
  `data_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_grupo`),
  KEY `fk_grupo_endereco` (`id_endereco`),
  CONSTRAINT `fk_grupo_endereco` FOREIGN KEY (`id_endereco`) REFERENCES `endereco` (`id_endereco`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================================
-- 2. COLABORADOR E PERMISSÕES
-- ========================================

CREATE TABLE `colaborador` (
  `id_colaborador` bigint NOT NULL AUTO_INCREMENT,
  `id_filial` bigint NOT NULL,
  `id_departamento` bigint,
  `id_perfil` bigint NOT NULL,
  `nome` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `senha_hash` varchar(255) NOT NULL,
  `tipo_colaborador` enum('Funcionario','Comissionado') NOT NULL DEFAULT 'Funcionario',
  `cargo` varchar(100),
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `data_cadastro` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_ultimo_login` timestamp NULL,
  `id_endereco` bigint,
  PRIMARY KEY (`id_colaborador`),
  UNIQUE KEY `uk_email` (`email`),
  KEY `fk_colaborador_filial` (`id_filial`),
  KEY `fk_colaborador_departamento` (`id_departamento`),
  KEY `fk_colaborador_perfil` (`id_perfil`),
  CONSTRAINT `fk_colaborador_departamento` FOREIGN KEY (`id_departamento`) REFERENCES `departamento` (`id_departamento`),
  CONSTRAINT `fk_colaborador_filial` FOREIGN KEY (`id_filial`) REFERENCES `filial` (`id_filial`),
  CONSTRAINT `fk_colaborador_perfil` FOREIGN KEY (`id_perfil`) REFERENCES `perfil_acesso` (`id_perfil`),
  CONSTRAINT `fk_colaborador_endereco` FOREIGN KEY (`id_endereco`) REFERENCES `endereco` (`id_endereco`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `funcao_sistema` (
  `id_funcao` bigint NOT NULL AUTO_INCREMENT,
  `modulo` enum('Cadastro','Comercial','Operacional','Financeiro','Relatorios','Configuracoes','Indicadores','Automacoes','Mensageria') NOT NULL,
  `nome_funcao` varchar(200) NOT NULL,
  `chave` varchar(100) NOT NULL,
  `tipo` enum('botao','menu','relatorio','configuracao') NOT NULL,
  `descricao` text,
  PRIMARY KEY (`id_funcao`),
  UNIQUE KEY `uk_chave` (`chave`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `perfil_permissao` (
  `id_perfil` bigint NOT NULL,
  `id_funcao` bigint NOT NULL,
  `pode_visualizar` tinyint(1) NOT NULL DEFAULT '0',
  `pode_incluir` tinyint(1) NOT NULL DEFAULT '0',
  `pode_alterar` tinyint(1) NOT NULL DEFAULT '0',
  `pode_excluir` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_perfil`,`id_funcao`),
  KEY `fk_perfil_perm_funcao` (`id_funcao`),
  CONSTRAINT `fk_perfil_perm_perfil` FOREIGN KEY (`id_perfil`) REFERENCES `perfil_acesso` (`id_perfil`) ON DELETE CASCADE,
  CONSTRAINT `fk_perfil_perm_funcao` FOREIGN KEY (`id_funcao`) REFERENCES `funcao_sistema` (`id_funcao`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================================
-- 3. LEAD E CLIENTE
-- ========================================

CREATE TABLE `lead` (
  `id_lead` bigint NOT NULL AUTO_INCREMENT,
  `id_colaborador` bigint,
  `id_filial` bigint NOT NULL,
  `nome_empresa_lead` varchar(255),
  `nome_contato_lead` varchar(255),
  `cnpj_lead` varchar(20),
  `email_lead` varchar(255),
  `telefone_lead` varchar(20),
  `whatsapp_lead` varchar(20),
  `origem` enum('Formulário','Indicação','Campanha','RedeSocial','Evento','Feira','Outros') NOT NULL,
  `regiao` enum('Norte','Nordeste','CentroOeste','Sudeste','Sul') ,
  `status_id` bigint NOT NULL,
  `motivo_perda` varchar(255),
  `observacoes` text,
  `data_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_conversao` timestamp NULL,
  `flag_classificado` tinyint(1) NOT NULL DEFAULT '0',
  `id_endereco` bigint,
  PRIMARY KEY (`id_lead`),
  KEY `fk_lead_colaborador` (`id_colaborador`),
  KEY `fk_lead_filial` (`id_filial`),
  KEY `fk_lead_status` (`status_id`),
  CONSTRAINT `fk_lead_colaborador` FOREIGN KEY (`id_colaborador`) REFERENCES `colaborador` (`id_colaborador`),
  CONSTRAINT `fk_lead_filial` FOREIGN KEY (`id_filial`) REFERENCES `filial` (`id_filial`),
  CONSTRAINT `fk_lead_status` FOREIGN KEY (`status_id`) REFERENCES `status` (`id_status`),
  CONSTRAINT `fk_lead_endereco` FOREIGN KEY (`id_endereco`) REFERENCES `endereco` (`id_endereco`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `lead_log_consulta_endereco` (
  `id_log` bigint NOT NULL AUTO_INCREMENT,
  `id_lead` bigint NOT NULL,
  `api_usada` varchar(50) NOT NULL,
  `status_resposta` varchar(50),
  `mensagem_erro` text,
  `data_tentativa` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`),
  KEY `fk_log_lead` (`id_lead`),
  CONSTRAINT `fk_log_lead` FOREIGN KEY (`id_lead`) REFERENCES `lead` (`id_lead`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cliente` (
  `id_cliente` bigint NOT NULL AUTO_INCREMENT,
  `id_filial` bigint NOT NULL,
  `id_colaborador` bigint,
  `id_grupo` bigint,
  `nome_empresa` varchar(255) NOT NULL,
  `nome_fantasia` varchar(255),
  `cnpj` varchar(20) NOT NULL,
  `ie` varchar(20),
  `contato_gestor` varchar(255),
  `contato_testemunha` varchar(255),
  `contato_financeiro` varchar(255),
  `email_gestor` varchar(255),
  `email_testemunha` varchar(255),
  `email_financeiro` varchar(255),
  `telefone_gestor` varchar(20),
  `telefone_testemunha` (`varchar`(20)),
  `telefone_financeiro` varchar(20),
  `regiao` enum('Norte','Nordeste','CentroOeste','Sudeste','Sul'),
  `status_id` bigint NOT NULL,
  `data_cadastro` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_status` timestamp NULL,
  `id_lead_origem` bigint,
  `id_endereco` bigint NOT NULL,
  `outras_informacoes` text,
  PRIMARY KEY (`id_cliente`),
  UNIQUE KEY `uk_cliente_cnpj_filial` (`cnpj`,`id_filial`),
  KEY `fk_cliente_filial` (`id_filial`),
  KEY `fk_cliente_colaborador` (`id_colaborador`),
  KEY `fk_cliente_grupo` (`id_grupo`),
  KEY `fk_cliente_status` (`id_status`),
  CONSTRAINT `fk_cliente_colaborador` FOREIGN KEY (`id_colaborador`) REFERENCES `colaborador` (`id_colaborador`),
  CONSTRAINT `fk_cliente_filial` FOREIGN KEY (`id_filial`) REFERENCES `filial` (`id_filial`),
  CONSTRAINT `fk_cliente_grupo` FOREIGN KEY (`id_grupo`) REFERENCES `grupo_economico` (`id_grupo`),
  CONSTRAINT `fk_cliente_lead_origem` FOREIGN KEY (`id_lead_origem`) REFERENCES `lead` (`id_lead`),
  CONSTRAINT `fk_cliente_status` FOREIGN KEY (`id_status`) REFERENCES `status` (`id_status`),
  CONSTRAINT `fk_cliente_endereco` FOREIGN KEY (`id_endereco`) REFERENCES `endereco` (`id_endereco`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cliente_grupo_economico` (
  `id_cliente` bigint NOT NULL,
  `id_grupo` bigint NOT NULL,
  PRIMARY KEY (`id_cliente`,`id_grupo`),
  CONSTRAINT `fk_cge_cliente` FOREIGN KEY (`id_cliente`) REFERENCES `cliente` (`id_cliente`) ON DELETE CASCADE,
  CONSTRAINT `fk_cge_grupo` FOREIGN KEY (`id_grupo`) REFERENCES `grupo_economico` (`id_grupo`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================================
-- END OF SCHEMA (continuação nas próximas seções)
-- Run: mysql -u root -p < crm_cpm_mensageria_schema.sql
-- Next: SEED DATA + BACKEND API

